### ISSUE TITLE
go 実装の isutomo 初期化時のバグについて

### ISSUE THREAD

**Issue by Muratam** [yahoojapan/yisucon#9]
https://github.com/yahoojapan/yisucon/blob/master/webapp/go/isutomo/app.go#L297

```
exec.Command(path, "-u", "root", "-D", "isutomo", "<", "../../sql/seed_isutomo2.sql").Run()
if err != nil {
	errorResponseWriter(w, http.StatusInternalServerError, err)
	return
}
```

となっていますが, まず err を取得していないバグがあり,
```
err = exec.Command(path, "-u", "root", "-D", "isutomo", "<", "../../sql/seed_isutomo2.sql").Run()
```
ではないでしょうか.

さらに, golang実装だけ `seed_isutomo2.sql` となっており,明らかに `seed_isutomo.sql` の間違いではないでしょうか.

**Comment by patapata23** [comment]
ご指摘ありがとうございます
修正が大変遅くなりすみません

こちら
#10
#11
にて不具合修正しました
